# Generated by Django 5.0.6 on 2024-05-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('tax_id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=100)),
                ('head', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('PaidIn_capital', models.IntegerField(default=None)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
    ]
